---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: api-gatway
  name: api-gatway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gatway
  template:
    metadata:
      labels:
        app: api-gatway
    spec:
      containers:
        - image: maheshkasbe/api-gatway:latest
          imagePullPolicy: Always
          name: api-gatway
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: api-gatway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: api-gatway
