---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: bug-service
  name: bug-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bug-service
  template:
    metadata:
      labels:
        app: bug-service
    spec:
      containers:
        - image: maheshkasbe/bug-service:latest
          imagePullPolicy: Always
          name: bug-service
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: bug-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8083
  selector:
    app: bug-service
