---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: project-service
  name: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - image: maheshkasbe/project-service:latest
          imagePullPolicy: Always
          name: user-service
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: project-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: project-service
