---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: service-registry
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - image: maheshkasbe/serviceRegistry:latest
          imagePullPolicy: Always
          name: service-registry
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  ports:
    - port: 80
      targetPort: 8761
  selector:
    app: service-registry
