---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: maheshkasbe/user-service:latest
          imagePullPolicy: Always
          name: user-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: user-service
